from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
 
class Ui_PendaftaranUKM(object):
    def submit(self):
        nama_lengkap = self.txt_nama.toPlainText()
        nim = self.txt_nama_2.toPlainText()
        program_studi = self.txt_nama_3.toPlainText()
        ukm_pilihan = self.txt_nama_4.toPlainText()
        alasan = self.txt_nama_5.toPlainText()
        nomor_hp = self.txt_nama_6.toPlainText()
 
        insert=(nama_lengkap, nim, program_studi, ukm_pilihan, alasan, nomor_hp)
        print(insert)
 
        con = pymysql.connect(host='localhost', user='root', passwd='', db='pendaftaran', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO pendaftaran_ukm(nama_lengkap, nim, program_studi, ukm_pilihan, alasan, nomor_hp)"+ \
        "VALUES"+str(insert)
        data = cur.execute(sql)
        if(data):
            self.kotakpesan("Sukses!", "Data Tersimpan")
        else:
            self.kotakpesan("Gagal", "Data Gagal Tersimpan")
 
    def kotakpesan(self, judul, isi):
        pesan = QtWidgets.QMessageBox()
        pesan.setWindowTitle(judul)
        pesan.setText(isi)
        pesan.setStandardButtons(QtWidgets.QMessageBox.Ok)
        pesan.exec_()
 
    def setupUi(self, PendaftaranUKM):
        PendaftaranUKM.setObjectName("PendaftaranUKM")
        PendaftaranUKM.resize(900, 700)
        PendaftaranUKM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        PendaftaranUKM.setStyleSheet("background-color: rgb(255, 171, 171);")
        self.centralwidget = QtWidgets.QWidget(PendaftaranUKM)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 611, 71))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(79, 54, 54);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(79, 54, 54);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 230, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(79, 54, 54);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 280, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(79, 54, 54);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 350, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(79, 54, 54);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 400, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(79, 54, 54);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 500, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(79, 54, 54);")
        self.label_7.setObjectName("label_7")
        self.txt_nama = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama.setGeometry(QtCore.QRect(480, 160, 311, 41))
        self.txt_nama.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama.setObjectName("txt_nama")
        self.btn_ukm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ukm.setGeometry(QtCore.QRect(710, 580, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.btn_ukm.setFont(font)
        self.btn_ukm.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.btn_ukm.clicked.connect(self.submit)
        self.btn_ukm.setObjectName("btn_ukm")
        self.txt_nama_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama_2.setGeometry(QtCore.QRect(480, 220, 311, 41))
        self.txt_nama_2.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama_2.setObjectName("txt_nama_2")
        self.txt_nama_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama_3.setGeometry(QtCore.QRect(480, 280, 311, 41))
        self.txt_nama_3.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama_3.setObjectName("txt_nama_3")
        self.txt_nama_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama_4.setGeometry(QtCore.QRect(480, 340, 311, 41))
        self.txt_nama_4.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama_4.setObjectName("txt_nama_4")
        self.txt_nama_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama_5.setGeometry(QtCore.QRect(480, 400, 311, 81))
        self.txt_nama_5.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama_5.setObjectName("txt_nama_5")
        self.txt_nama_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_nama_6.setGeometry(QtCore.QRect(480, 500, 311, 41))
        self.txt_nama_6.setStyleSheet("background-color: rgb(255, 228, 228);")
        self.txt_nama_6.setObjectName("txt_nama_6")
        PendaftaranUKM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PendaftaranUKM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menubar.setObjectName("menubar")
        PendaftaranUKM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PendaftaranUKM)
        self.statusbar.setObjectName("statusbar")
        PendaftaranUKM.setStatusBar(self.statusbar)
 
        self.retranslateUi(PendaftaranUKM)
        QtCore.QMetaObject.connectSlotsByName(PendaftaranUKM)
 
    def retranslateUi(self, PendaftaranUKM):
        _translate = QtCore.QCoreApplication.translate
        PendaftaranUKM.setWindowTitle(_translate("PendaftaranUKM", "MainWindow"))
        self.label.setText(_translate("PendaftaranUKM", "FORM PENDAFTARAN UKM ITK"))
        self.label_2.setText(_translate("PendaftaranUKM", "Nama Lengkap                         :"))
        self.label_3.setText(_translate("PendaftaranUKM", "NIM                                         :"))
        self.label_4.setText(_translate("PendaftaranUKM", "Program Studi                          :"))
        self.label_5.setText(_translate("PendaftaranUKM", "UKM yang Diminati                   :"))
        self.label_6.setText(_translate("PendaftaranUKM", "Alasan Mendaftar UKM              :"))
        self.label_7.setText(_translate("PendaftaranUKM", "No Telepon/WA                         :"))
        self.btn_ukm.setText(_translate("PendaftaranUKM", "SUBMIT"))
 
 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PendaftaranUKM = QtWidgets.QMainWindow()
    ui = Ui_PendaftaranUKM()
    ui.setupUi(PendaftaranUKM)
    PendaftaranUKM.show()
    sys.exit(app.exec_())
